class Repository:
    def add_entry(self, new_object):
        ...

    def remove_entry(self, object_id):
        ...

    def update_entry(self, object_id, new_object):
        ...

    def get_all_entries(self):
        ...

    def find_entry_by_id(self, object_id):
        ...
